### ISSUE TITLE
koi-8 encoding

### ISSUE THREAD

**Issue by hardway777** [higty/higlabo.netstandard#1]
Source:
```
Subject: =?koi8-r?B?0M/XwcfPzsvBINrBIDAxLTA2LjA1IC0gxy/PIOLVzsfV0tPLycogKO7P188=?=
        =?koi8-r?B?y9XazsXDyy3Tz9LULik=?=
```
![0000001](https://user-images.githubusercontent.com/198486/40459245-a5a19690-5f43-11e8-8a8c-5b94d483e826.png)

Correct text is:
```повагонка за 01-06.05 - г/о Бунгурский (Новокузнецк-сорт.)```

Wrong text is: 
```повагонка за 01-06.05 - г/о Бунгурский (Ново\0кузнецк-сорт.```

![0000002](https://user-images.githubusercontent.com/198486/40459299-f58934c4-5f43-11e8-9ff7-a33ee2798b1b.png)

**Comment by hardway777** [comment]
Part of source of other mail 

![000003](https://user-images.githubusercontent.com/198486/40459779-9b95396a-5f46-11e8-944b-a90b414a46a1.png)

```
------=_NextPart_000_04FC_01D3E6CA.9843D180
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;
        name="=?koi8-r?B?79TH0tXay8EgzsEg7dnTIOHT1MHG2MXXwSDXIO3BxSAyMDE4IPTt8w==?=
        =?koi8-r?B?+yAxMSUgMTU1MyAo5ffy4fopLnhsc3g=?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
        filename="=?koi8-r?B?79TH0tXay8EgzsEg7dnTIOHT1MHG2MXXwSDXIO3BxSAyMDE4IPTt8w==?=
        =?koi8-r?B?+yAxMSUgMTU1MyAo5ffy4fopLnhsc3g=?="
```
Wront text:
```\"Отгрузка на Мыс Астафьева в Мае 2018 ТМС```

Valid filename is
```Отгрузка на Мыс Астафьева в Мае 2018 ТМСШ 11% 1553 (ЕВРАЗ).xlsx```

**Comment by higty** [comment]
Hi VladimirPobedins.
Thank you for your detailed report!It is great that make me easy to understand your problem.
I'll add test case and solve this issue in few days.

regards.

**Comment by higty** [comment]
I created three test case.
```
[TestMethod]
public void Rfc2047Converter_Basic5()
{
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

    Rfc2047Converter cv = new Rfc2047Converter();

    Assert.AreEqual("Отчёт о движении вагонов с углём АО \"Сибуглемет\" на терминале ООО \"ВСК\""
        , cv.Decode("=?utf-8?B?0J7RgtGH0ZHRgiDQviDQtNCy0LjQttC10L3QuNC4INCy0LDQ?=\r\n "
        + "=?utf-8?B?s9C+0L3QvtCyINGBINGD0LPQu9GR0Lwg0JDQniAi0KHQuNCx0YPQs9C7?=\r\n " 
        + "=?utf-8?B?0LXQvNC10YIiINC90LAg0YLQtdGA0LzQuNC90LDQu9C1INCe0J7QniAi?=\r\n " 
        + "=?utf-8?B?0JLQodCaIg==?=\r\n"));
}
[TestMethod]
public void Rfc2047Converter_Basic6()
{
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

    Rfc2047Converter cv = new Rfc2047Converter();

    Assert.AreEqual("повагонка за 01-06.05 - г/о Бунгурский (Новокузнецк-сорт.)"
        , cv.Decode(" =?koi8-r?B?0M/XwcfPzsvBINrBIDAxLTA2LjA1IC0gxy/PIOLVzsfV0tPLycogKO7P188=?=\r\n"
        + "        =?koi8-r?B?y9XazsXDyy3Tz9LULik=?="));
}
```

In previous version(2.0.0), I decode with logic like below.
1.Decode each line
2.Concat decoded text.

Current version(2.0.1), I change logic like below
1.Concat all line if Charset(koi8-r) and decoder(B=Base64) is same.
2.Decode

Previous version(2.0.0) pass test case of Basic6.Current version pass Basic5.
It looks like invalid encoder that encode middle of char and separate 2 bytes char.

I'll continue to solve problem.The goal is to parse such a invalid text encoding.
Please wait more few days.


regard.

**Comment by higty** [comment]
I fixed for Rfc2047Converter_Basic5, Rfc2047Converter_Basic6 test case and upload latest version as HigLabo.Converter(2.0.1.1).

Next, I will try to solve problem about file name.This file name is invalid that is encoded by RFC2047.Encoder must encode with RFC2231.But I modify HigLabo.Converter to handle it.

**Comment by hardway777** [comment]
Hi **higty**. What progress with handling filenames?

**Comment by higty** [comment]
Hi.
Sorry, I could not have a time to do it recently.
But I finished my work and I will have a time to do it.
So, please wait few days.

**Comment by higty** [comment]
I modified and commit to master branch.
And I uploaded latest version of Nugut.
Thank you for your contribution.

regards.

**Comment by hardway777** [comment]
Missing tab or space between blocks
String
```=?koi8-r?B?8M/XwcfPzs7B0SDT0MXDycbJy8HDydEg/e/mLfPJwtXHzMXNxdRfMDYueGw=?=\r\n\t=?koi8-r?B?c3g=?=```
Wrong parsed into 
```Повагонная спецификация ЩОФ-Сибуглемет_06.xl=?koi8-r?B?c3g```

Right string is
```Повагонная спецификация ЩОФ-Сибуглемет_06.xlsx```

![image](https://user-images.githubusercontent.com/198486/41637667-5c918450-7498-11e8-99ae-82aac7d5392b.png)

**Comment by higty** [comment]
Hi.

Thank you for your report.Pretty good bug report this help me to fix it easy.
I will add test case and fix it.
Please wait...

PS. Congraturation for Russia won 3-1 against Egypt on World CUP!!!

**Comment by hardway777** [comment]
thanks)

**Comment by hardway777** [comment]
higty, can you today fix this bug?

**Comment by higty** [comment]
Hi.

I just on going for this issue.Maybe today.

**Comment by higty** [comment]
Hi! I fixed and commit source code.
And I uploaded Nuget package as HigLabo.Converter 2.0.1.2.

regards.
