### ISSUE TITLE
How to get messages headers only?

### ISSUE THREAD

**Issue by hardway777** [higty/higlabo.netstandard#2]
How to get messages headers only? Without full message body and attachments.

**Comment by higty** [comment]
Hi.

Maybe ImapClient class has command to get header only.I'll create sample code later within few days.
If there is no feature to get header only, I'll add this feature.

And here is a article I posted about IMAP.
https://www.codeproject.com/Articles/411018/Understanding-the-insides-of-the-IMAP-mail-protoco

regards.

**Comment by hardway777** [comment]
> If there is no feature to get header only, I'll add this feature.

Thanks. I'll wait this feature.

**Comment by higty** [comment]
Hi.

It is a sample code to get mail header.

            using (ImapClient cl = new ImapClient("imap.xxx.com"))
            {
                cl.UserName = "xxx@gmail.com";
                cl.Password = "xxx";
                var bl = cl.TryAuthenticate();
                if (bl == true)
                {
                    //Select folder
                    var folder = cl.SelectFolder("YourFolder");
                    //Get all mail header
                    var mailIndex = 1;
                    var headers = cl.GetHeaderCollection(mailIndex);
                }
            }

regards.

**Comment by higty** [comment]
Closed.
